### ISSUE TITLE
Can see in BLE scanner app but not in PhysicalWeb app?

### ISSUE THREAD

**Issue by AdySan** [angst7/Phatbeacon#2]
Hi Matt, 

 Just tried this on my nRF52-DK. As you can see in the screenshot, I can see the EddyStone Beacon on the nRF Connect app but nothing on the PhysicalWeb app. Am I missing something here? I was assuming I'd see some sort of URL in the PhysicalWeb app.

![photo oct 23 9 52 38 pm](https://cloud.githubusercontent.com/assets/744810/19633936/54b54942-996b-11e6-8ac3-7e5d2c7dac0b.png)
![photo oct 23 9 52 49 pm](https://cloud.githubusercontent.com/assets/744810/19633937/54b9a208-996b-11e6-81c2-524463ae33ae.png)

**Comment by angst7** [comment]
Have you enabled Fatbeacon in the Physical Web scanner settings?

**Comment by AdySan** [comment]
I’m sorry, I can’t seem to find the scanner settings, neither in Chrome nor in the Physical Web app on iOS. Don’t own an Android device, so can’t test that either.

**Comment by AdySan** [comment]
Hmm, looking at the Physical Web repo, looks like as of now only the Android app has these settings. Nevermind then.

**Comment by angst7** [comment]
Yes, Fatbeacon is experimental.  I'm not surprised they haven't added it to iOS yet.

**Comment by AdySan** [comment]
I’m sorry, I can’t seem to find the scanner settings, neither in Chrome nor in the Physical Web app on iOS. Don’t own an Android device, so can’t test that either.
